version: "3"
services:
  #SQL Server
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=WR2WPMjrJUoB27
      - POSTGRES_USER=postgres
      - POSTGRES_DB=backendtest
    restart: unless-stopped
  # Frontend
  formdesign-backend:
    image: knoph/formdesign-backend:latest
    network_mode: bridge
    container_name: formdesign-backend
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
  # Backend
  formdesign-frontend:
    image: knoph/formdesign-frontend:latest
    network_mode: bridge
    container_name: formdesign-frontend
    expose:
      - 80
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - formdesign-backend
    links:
      - formdesign-backend
volumes:
  postgres-data: